# Comment to a new issue.
issuesOpened: >
  Thank your for raising this issue. We will review this and get back to you as soon as possible.

  Please make sure you have given us as much context as possible and followed our issue template.

pullRequestOpened: >
  Thank you for raising your pull request.

  Please make sure you have followed our contributing guidelines. We will review it as soon as possible.
