version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:8
    working_directory: ~/doc-it-dev
    environment:
      - SOURCE_BRANCH: master
      - DEV_TARGET: https://github.com/px-blue/px-blue.github.io
      - MASTER_TARGET: https://github.com/pxblue/pxblue.github.io
      - GH_EMAIL: pxblue@eaton.com
      - GH_NAME: PX Blue Agent
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email "$GH_EMAIL"
              git config --global user.name "$GH_NAME"
              
              git clone $MASTER_TARGET out

              cd out
              git rm -rf .
              cd ..

              npm run build

              cp -a build/. out/.
              cd out

              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
              git push
            fi
